import argparse
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ed25519, rsa


def generate_keypair(key_type: str, out_dir: Path) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)

    if key_type == "ed25519":
        private_key = ed25519.Ed25519PrivateKey.generate()
    elif key_type == "rsa":
        private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    else:
        raise ValueError(f"Unsupported key type: {key_type}")

    public_key = private_key.public_key()

    private_path = out_dir / f"binance_testnet_{key_type}_private.pem"
    public_path = out_dir / f"binance_testnet_{key_type}_public.pem"

    private_bytes = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )

    private_path.write_bytes(private_bytes)
    public_path.write_bytes(public_bytes)
    return private_path, public_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Binance Spot Testnet RSA/Ed25519 keypair")
    parser.add_argument(
        "--type",
        choices=("ed25519", "rsa"),
        default="ed25519",
        help="Asymmetric key type for Binance testnet",
    )
    parser.add_argument(
        "--out-dir",
        default=".secrets/binance_testnet",
        help="Directory to store generated private/public key files",
    )
    args = parser.parse_args()

    out_dir = Path(args.out_dir).expanduser().resolve()
    private_path, public_path = generate_keypair(args.type, out_dir)

    print("created-private-key:", private_path)
    print("created-public-key:", public_path)
    print("next-step: log in to https://testnet.binance.vision/ and register the PUBLIC key")
    print(f"env: BINANCE_USE_TESTNET=true")
    print(f"env: BINANCE_TESTNET_KEY_TYPE={args.type}")
    print(f"env: BINANCE_TESTNET_PRIVATE_KEY_PATH={private_path}")
    print("env: BINANCE_TESTNET_API_KEY=<paste the API key generated by Binance testnet>")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
